name: 'Baidu Tieba Auto Sign'

on:
  push:
    branches:
      - main
  schedule:
    - cron: '5 2,10 * * *'
  workflow_dispatch:

jobs:
  tieba_sign:
    runs-on: ubuntu-latest
    steps:
      - name: 'Set timezone'
        uses: szenius/set-timezone@v1.2
        with:
          timezoneLinux: 'Asia/Shanghai'
          timezoneMacos: "Asia/Shanghai"
      - name: 'Checkout codes'
        uses: actions/checkout@v3
      - name: 'Set python'
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: 'Install dependencies'
        run: python3 -m pip install --upgrade requests
      - name: 'Start Sign'
        env:
          BDUSS: ${{ secrets.BDUSS }}
        run: python3 main.py
      - name: 'keep alive workflow'
        uses: gautamkrishnar/keepalive-workflow@v1
